name: build-deploy
run-name: ${{ github.actor }} is build and deploy
on:
  push:
    branches:
      - "production"

jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular ssr Project
        run: npm run build:ssr

      - name: copy file via ssh key
        uses: appleboy/scp-action@master

        with:

          host: 35.219.224.72
          username: etmana
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          port: 22

          proxy_host: 34.154.126.85
          proxy_username: etmana
          proxy_key: ${{ secrets.JUMP_KEY}}

          source: "./dist"
          target: "/var/www/etmana-front/test"


